version: '3.4'

services:
  rabbitmq:
    image: "rabbitmq:3.9-management"
    hostname: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  doctorservicepostgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: doctorservice

  doctorservice.api:
    image: ${DOCKER_REGISTRY-}doctorserviceapi
    build:
      context: .
      dockerfile: DoctorService.API/Dockerfile
    environment:
      - DOCKER_ENVIROMENT=DOCTOR_DOCKER_ENV
    depends_on:
      - doctorservicepostgres
    ports:
        - "5020:80"
        - "5021:443"

  patientservicepostgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: patientservice

  patientservice.api:
    image: ${DOCKER_REGISTRY-}patientserviceapi
    build:
      context: .
      dockerfile: PatientService.API/Dockerfile
    environment:
      - DOCKER_ENVIROMENT=PATIENT_DOCKER_ENV
    depends_on:
      - patientservicepostgres
    ports:
        - "5030:80"
        - "5031:443"
